name: Deploy to host server

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    environment: deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install deps
        run: |
          npm install --save-dev typescript pug-cli tailwindcss@3 postcss autoprefixer
      
      - name: Build site
        run: npm run build

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ vars.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/deploy_key" dist/ ${{ secrets.DEPLOY_USER }}@${{ vars.SERVER_HOST }}:~/www/vpert-site/
